"""Initial migration

Revision ID: 1d8111f8183e
Revises: e00ab2697f7a
Create Date: 2024-06-12 19:00:18.738708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8111f8183e'
down_revision: Union[str, None] = 'e00ab2697f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('source_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source', 'source_description')
    # ### end Alembic commands ###
